[[docs]]
  name = "Pr贸logo"
  weight = 1
  identifier = "prologo"
  url = "/docs/prologo/"

[[docs]]
  name = "Intro a la Programaci贸n"
  weight = 2
  identifier = "intro"
  url = "/docs/intro/"

[[docs]]
  name = "La STL"
  weight = 3
  identifier = "stl"
  url = "/docs/stl/"

[[docs]]
  name = "Paradigmas de Resoluci贸n"
  weight = 4
  identifier = "paradigmas"
  url = "/docs/paradigmas"

[[docs]]
  name = "Estructuras de Datos"
  weight = 5
  identifier = "estructuras"
  url = "/docs/ds"

[[docs]]
  name = "Grafos"
  weight = 6
  identifier = "grafos"
  url = "/docs/grafos"

[[docs]]
  name = "Extras"
  weight = 998
  identifier = "extras"
  url = "/docs/extras/"

[[docs]]
  name = "Anexos"
  weight = 999
  identifier = "anexos"
  url = "/docs/anexos/"

[[recursos]]
  name = "Pr贸logo"
  weight = 1
  identifier = "prologo"
  url = "/recursos/prologo"

[[recursos]]
  name = "Websites"
  weight = 2
  identifier = "websites"
  url = "/recursos/websites"

[[main]]
  name = "Apunte"
  url = "/docs/prologo/intro"
  weight = 1

[[main]]
name = "Recursos"
url = "/recursos/prologo/intro"
weight = 2

[[main]]
  name = "CSES"
  url = "/cses"
  weight = 3

[[main]]
  name = "Acerca"
  url = "/acerca"
  weight = 4

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/progcompuch/apunte"
  weight = 1
